### PR TITLE
Fix Floor Generator Bot

### PR DESCRIPTION
**Pull request by theCapypara**
This fixes the floor generator bot, by upgrading to the latest SkyTemple Files version.

### CODE REVIEW

**Comment by Frostbyte0x70** [comment]
Can you rebase on top of the new main branch? I had to fix a couple things to get the test env working

**Comment by theCapypara** [comment]
Done

**Comment by Frostbyte0x70** [comment]
Alright, I tested it and it no longer gives an error.
But now some strange tiles are displayed, not sure why.

Old version, no items:
ZiC 1F - old version, no items

New version, no items:
ZiC 1F - new version, no items

New version, items:
ZiC 1F - new version, items

**Comment by theCapypara** [comment]
I'll check.

**Review by Frostbyte0x70 — APPROVED** [review]
Thanks!

**Pull request merged**
