### PR TITLE
Remove migrated or discontinued features

### PR DESCRIPTION
**Pull request by End45**
In preparation for the introduction of [Altaria](https://github.com/SkyTemple/altaria), the following fieatures will be disabled, either because they have been migrated to the new bot or because they will be discontinued:

- Reputation: Migrated to Altaria (the leaderboard on the website has been replaced with a command)
- 🎉?: Requires reading too many messages
- "Using SkyTemple" role: Floods the audit log

The features remaining in Swablu will be related to the website and hack management. Ideally, those would be rewritten at some point so a Discord bot isn't required to view and manage the site, but that's out of the scope of this migration.

### CODE REVIEW

**Comment by theCapypara** [comment]
Will the Crowdin webhook and the reputation API stay in Swablu or also be moved to Altaria? If I need to configure new URLs for this, please let me know.

**Comment by End45** [comment]
> Crowdin webhook

No changes there, Swablu will continue to post the messages.

> Reputation API

You mean https://hacks.skytemple.org/guildpoints? I said above, that will be disabled. Does anyone use the JSON version of it?

**Comment by theCapypara** [comment]
The SpriteServer and via that https://sprites.pmdcollab.org/#/Contributors uses it.

**Comment by End45** [comment]
I see. I don't think it makes much sense to use GP to sort that list since they aren't used for just spriting.
@keldaan-ag Would the page break badly if this gets removed?

**Comment by End45** [comment]
Looking at [the code](https://github.com/PMDCollab/PMD-collab-wiki/blob/master/src/generated/graphql.tsx), it seems like it's built to handle the case where reputation is missing, so I'll make the change and hopefully another way of sorting the credits is eventually implemented. As long as the credits page doesn't break completely, it should be alright for now.

**Pull request merged**
